name: Run Custom Command

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      CMD:
        description: 'The command you want to run'
        required: false
        default: ''

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Execute custom command
        run: |
          if [ -z "${{ github.event.inputs.CMD }}" ]; then
            ${{ secrets.CMD }}
          else
            ${{ github.event.inputs.CMD }}
          fi
