name: Run Custom Command

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      cmd:
        description: 'The command you want to run'
        required: true
        default: 'echo "Hello, World!"'

jobs:
  run-command:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
      
      - name: Execute custom command
        run: |
          if [ -z "${{ github.event.inputs.cmd }}" ]; then
            echo "Using secret"
            ${{ secrets.cmd }}
          else
            echo "Using input"
            ${{ github.event.inputs.cmd }}
          fi
